import Head from 'next/head'
import Layout from '@/Components/Layout'
import Image from 'next/image'
import ProfilePic from '../../public/images/profile/adeola.png'
import AnimatedText from '@/Components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/Components/Icons'
import HireMe from '@/Components/HireMe'
import LightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
            <div className='flex items-center w-full justify-between lg:flex-col'>
              <div className='w-1/2 md:w-full'>

                <Image src={ProfilePic} alt='Adeola' className='w-full h-auto 
                  lg:hidden md:inline-block md:w-full' priority
                  sizes='(max-width: 768px) 100vw, (max-width: 1200px) 50vw,'
                />
              </div>

              <div className='w-1/2 flex flex-col items-center self-center lg:text-center'>
                <AnimatedText text='Turning Vision And Design Into Reality With Code.' 
                className='!text-left !text-6xl xl:!text-5xl 
                lg:!text-center lg:!text-6xl md:!text-3xl sm:!text-2xl'/>

                <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>As a skilled frontend developer, 
                I am dedicated to turning ideas into innovative web applications. 
                Explore my latest projects, showcasing my expertise in React.js/TypeScript and web development.</p>

                <div className='flex items-center self-start mt-2 lg:self-center'>

                  <Link href='/adeola_CV.pdf' target='_blank' 

                    className='flex bg-dark text-light items-center 
                    hover:text-dark hover:bg-light 
                    p-2.5 px-6 rounded-lg md:p-2 md:px-4 
                    md:text-base text-lg font-semibold dark:bg-light
                    dark:text-dark hover:dark:bg-dark hover:dark:text-light
                    hover:dark:border-light border-2 border-solid border-transparent
                    hover:border-dark' download={true}>

                    Resume <LinkArrow className={'w-6 ml-1'}/>
                  </Link>

                  <Link href='mailto:adeola670@gmail.com' target='_blank'
                    className='font-medium text-dark underline ml-4 text-lg capitalize dark:text-light md:text-base'
                  >
                    Contact
                  </Link>
                </div>
              </div>
            </div>
        </Layout>
        <HireMe/>
        <div className='absolute right-8 bottom-8 inline-block w-24 md:hidden'>
          <Image src={LightBulb} alt='Adeola' className='w-full h-auto'></Image>
        </div>
      </main>
    </>
  )
}
